#!/bin/bash
# chmod ug+x git
clear

echo 'Stages & commits changes to current branch and pushes to origin'
echo '( BTW... This is really not considered good practice )'

git add . && git commit -m "Initial Release" && git push
